# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7876e9bcd7c57bebc3dc45e51f6f93118555dd5204c500486b2b573c6e655cb4b3197b09e756d9ed0358bd66fb687b87a39da0d1542a6753fc046c5fb8415b7

test:
  secret_key_base: 6f64a96b4fe8e34380825daf5f81129f05835998e78e1b93e0aeed02b8659b8b3444f09cf3b986582863a4e98bd57cc8988b0f7a0790f0ee27a5f3d8e128c289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
